#!/bin/bash -e
cd $(dirname $(readlink -f $0))/src/

if !(( $# )); then
    set -- "--help"
fi

#These shit can easily be done with bash
HELP="--help"
LIST="--list"

if [[ $1 == $LIST ]]; then
    cat ../localcoins.txt
elif [[ $1 == $HELP ]]; then
    echo "usage: clc [--help] [--list] [--remove] [--add]
           [-l, -c <ids>]"
else
    ./main $*
fi

