#!/bin/bash -e
cd $(dirname $(readlink -f $0))/src/

if !(( $# )); then
    set -- "--help"
fi

if [[ $1 == "--list" ]]; then
    cat ../localcoins.txt
elif [[ $1 == "--help" ]]; then
    echo "usage: clc [--help] [--list] [--remove] [--add]
           [-l, -c <ids>]"
else
    ./main $*
fi

